### ISSUE TITLE
pktgen not working in DPDK 17.08

### ISSUE THREAD

**Issue by shuwens** [shuwens/pktgen#2]
To recreate:
```sh
# in branch rework-17.08
$ make all
```
Error output:
```sh
src/pktgen.c: In function ‘find_port_id’:
src/pktgen.c:422:17: error: ‘struct rte_eth_dev’ has no member named ‘attached’
         if (!dev->attached)
                 ^
src/pktgen.c: In function ‘handle_client’:
src/pktgen.c:445:5: error: ‘rte_eth_dev_count’ is deprecated [-Werror=deprecated-declarations]
     uint8_t port_id, nb_ports = rte_eth_dev_count();
     ^
In file included from src/pktgen.h:44:0,
                 from src/pktgen.c:1:
/home/jethros/dev/openNetVM/dpdk/x86_64-native-linuxapp-gcc/include/rte_ethdev.h:1474:10: note: declared here
 uint16_t rte_eth_dev_count(void);
          ^
src/pktgen.c: In function ‘main’:
src/pktgen.c:619:5: error: ‘rte_eth_dev_count’ is deprecated [-Werror=deprecated-declarations]
     uint8_t nb_ports = rte_eth_dev_count();
     ^
In file included from src/pktgen.h:44:0,
                 from src/pktgen.c:1:
/home/jethros/dev/openNetVM/dpdk/x86_64-native-linuxapp-gcc/include/rte_ethdev.h:1474:10: note: declared here
 uint16_t rte_eth_dev_count(void);
          ^
cc1: all warnings being treated as errors
Makefile:29: recipe for target 'bin/pktgen' failed
make: *** [bin/pktgen] Error 1
```
